# Generated by Django 4.2.27 on 2026-01-18 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rule', models.CharField(choices=[('HIGH_WINS', 'Higher wins'), ('LOW_WINS', 'Lower wins')], max_length=20)),
                ('attacker_hand', models.JSONField(default=list)),
                ('defender_hand', models.JSONField(default=list)),
                ('attacker_card', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('defender_card', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('ATTACKER_WIN', 'Attacker wins'), ('DEFENDER_WIN', 'Defender wins'), ('DRAW', 'Draw')], max_length=20, null=True)),
                ('attacker_delta', models.IntegerField(default=0)),
                ('defender_delta', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_games', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='game_game_status_9bfe99_idx'), models.Index(fields=['attacker', 'status'], name='game_game_attacke_c7efc1_idx'), models.Index(fields=['defender', 'status'], name='game_game_defende_0d4b58_idx')],
            },
        ),
    ]
